# code: language=ansible
# SPDX-License-Identifier: 0BSD
---

- name: Generate systemd timer files
  notify:
    - Reload systemd
    - Enable systemd timers
  block:
    - name: Create systemd service
      loop: "{{ red55_systemd_timers }}"
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.template:
        src: "systemd.service.j2"
        dest: "/etc/systemd/system/{{ item.name }}.service"
        owner: root
        group: root
        mode: u=rw,go=r

    - name: Create systemd timer
      loop: "{{ red55_systemd_timers }}"
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.template:
        src: "systemd.timer.j2"
        dest: "/etc/systemd/system/{{ item.name }}.timer"
        owner: root
        group: root
        mode: u=rw,go=r
