# SPDX-License-Identifier: 0BSD
name: PR Molecule Test

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule[docker] requests

      - name: Run Molecule tests
        run: |
          molecule test -s default
